"""Baseline: the schema exactly as it stood at v1.2.

Hand-written rather than autogenerated so that it matches, statement for
statement, the `CREATE TABLE IF NOT EXISTS` script that shipped up to v1.2.
That equivalence is what lets `Store._stamp_legacy` adopt an existing database
instead of rebuilding it. `tests/test_migrations.py` compares a freshly
migrated database against `theater/daemon/schema.py` and fails if they drift.

Revision ID: 0001
Revises:
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "participants",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("harness", sa.Text(), nullable=False),
        sa.Column("tier", sa.Text(), nullable=False),
        sa.Column("tmux_pane", sa.Text(), nullable=True),
        sa.Column("cwd", sa.Text(), nullable=True),
        sa.Column("branch", sa.Text(), nullable=True),
        sa.Column("session_id", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.Text(), nullable=True),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("last_activity", sa.REAL(), nullable=False),
        sa.Column("created_at", sa.REAL(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_participants_pane", "participants", ["tmux_pane"])
    op.create_index("idx_participants_parent", "participants", ["parent_id"])
    op.create_index("idx_participants_status", "participants", ["status"])

    op.create_table(
        "jobs",
        sa.Column("handle", sa.Text(), nullable=False),
        sa.Column("caller_id", sa.Text(), nullable=False),
        sa.Column("target_id", sa.Text(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("created_at", sa.REAL(), nullable=False),
        sa.Column("finished_at", sa.REAL(), nullable=True),
        sa.PrimaryKeyConstraint("handle"),
    )
    op.create_index("idx_jobs_caller", "jobs", ["caller_id"])
    op.create_index("idx_jobs_state", "jobs", ["state"])

    op.create_table(
        "bus",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.REAL(), nullable=False),
        sa.Column("from_id", sa.Text(), nullable=True),
        sa.Column("to_id", sa.Text(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_index("idx_bus_ts", "bus", ["ts"])

    op.create_table(
        "budgets",
        sa.Column("tree_root_id", sa.Text(), nullable=False),
        sa.Column("tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cents", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("limit_cents", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("tree_root_id"),
    )


def downgrade() -> None:
    op.drop_table("budgets")
    op.drop_index("idx_bus_ts", table_name="bus")
    op.drop_table("bus")
    op.drop_index("idx_jobs_state", table_name="jobs")
    op.drop_index("idx_jobs_caller", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("idx_participants_status", table_name="participants")
    op.drop_index("idx_participants_parent", table_name="participants")
    op.drop_index("idx_participants_pane", table_name="participants")
    op.drop_table("participants")
