"""Claude Code built-in harness entrypoint."""

import json

from theater.harness.builtin.adapters.claude.constants import (
    _CWD_PROBE_BYTES,
    _CWD_PROBE_RECORDS,
    _LOSS_CANDIDATE_PROBES,
    _READ_TOOLS,
    _SCREEN_TAIL_LINES,
    _WRITE_TOOLS,
    APPROVAL_MARKER,
    CLAUDE_RECEIPT_COMMAND,
    CLAUDE_RECEIPT_EVENTS,
    IDLE_AGENTS_FOOTER,
    IDLE_FOOTER,
    IDLE_PROMPTS,
    MODE_LINE_PREFIXES,
    TRUST_MARKER,
    WORKING_MARKER,
)
from theater.harness.builtin.adapters.claude.launch import (
    ClaudeCodeHarness,
    _claude_receipt_settings,
    _claude_settings_path,
    _hook_string,
    _receipt_hook_command,
)
from theater.harness.builtin.adapters.claude.observer import ClaudeCodeObserver
from theater.harness.builtin.adapters.claude.source import _ClaudeSource
from theater.harness.builtin.adapters.claude.trajectory import (
    _claude_block_native_id,
    _claude_content_text,
    _claude_first_token,
    _claude_mcp_identity,
    _claude_request_bounds,
    _claude_request_id,
    _claude_request_timing_value,
    _claude_revision,
    _claude_timing,
    _claude_trajectory_usage,
    _claude_turn_timing,
    _ClaudeCausalRecord,
    _ClaudeRequestClock,
    _ClaudeTimingProjection,
    _epoch,
    _relativise,
    _remember_bounded,
    _safe_trajectory_text,
    _stable_json,
    _token_usage,
    _trajectory_detail,
    _trajectory_duration,
    _trajectory_float,
    _trajectory_id,
    _trajectory_int,
    _trajectory_status,
    _trajectory_time,
)

HARNESS = ClaudeCodeHarness()

__all__ = [
    "APPROVAL_MARKER",
    "CLAUDE_RECEIPT_COMMAND",
    "CLAUDE_RECEIPT_EVENTS",
    "HARNESS",
    "IDLE_AGENTS_FOOTER",
    "IDLE_FOOTER",
    "IDLE_PROMPTS",
    "MODE_LINE_PREFIXES",
    "TRUST_MARKER",
    "WORKING_MARKER",
    "_CWD_PROBE_BYTES",
    "_CWD_PROBE_RECORDS",
    "_LOSS_CANDIDATE_PROBES",
    "_READ_TOOLS",
    "_SCREEN_TAIL_LINES",
    "_WRITE_TOOLS",
    "ClaudeCodeHarness",
    "ClaudeCodeObserver",
    "_ClaudeCausalRecord",
    "_ClaudeRequestClock",
    "_ClaudeSource",
    "_ClaudeTimingProjection",
    "_claude_block_native_id",
    "_claude_content_text",
    "_claude_first_token",
    "_claude_mcp_identity",
    "_claude_receipt_settings",
    "_claude_request_bounds",
    "_claude_request_id",
    "_claude_request_timing_value",
    "_claude_revision",
    "_claude_settings_path",
    "_claude_timing",
    "_claude_trajectory_usage",
    "_claude_turn_timing",
    "_epoch",
    "_hook_string",
    "_receipt_hook_command",
    "_relativise",
    "_remember_bounded",
    "_safe_trajectory_text",
    "_stable_json",
    "_token_usage",
    "_trajectory_detail",
    "_trajectory_duration",
    "_trajectory_float",
    "_trajectory_id",
    "_trajectory_int",
    "_trajectory_status",
    "_trajectory_time",
    "json",
]
