"""MCP-server plugin contracts, loading, and independent registry."""

from theater.mcp_plugins.compiler import compile_manifest
from theater.mcp_plugins.config import (
    McpConfigResolutionError,
    parse_secret_reference,
    resolve_config,
    resolve_plugin_config,
)
from theater.mcp_plugins.contracts import (
    MANIFEST_API_VERSION,
    MCP_PLUGIN_API_VERSION,
    MISSING,
    PLUGIN_API_VERSION,
    CompiledMcpPlugin,
    ConfigField,
    ConfigKind,
    ConfigSchema,
    LaunchManifest,
    LaunchPlan,
    McpConfigField,
    McpConfigKind,
    McpConfigSchema,
    McpLaunchContext,
    McpLaunchManifest,
    McpLaunchPlan,
    McpLaunchPlanner,
    McpServerManifest,
    McpServerSpec,
    PluginCapability,
    SecretReference,
    SecretValue,
)
from theater.mcp_plugins.loading import (
    LOCAL,
    MANIFEST_FILENAME,
    SHIPPED,
    LoadedMcpPlugin,
    McpPluginError,
    discover,
    load_plugin,
    scan,
)
from theater.mcp_plugins.registry import (
    MCP_SERVERS,
    McpPluginCatalog,
    McpPluginDiagnostic,
    UnknownMcpServer,
    catalog,
    diagnostics,
    get,
    install,
)
from theater.mcp_plugins.validation import McpManifestValidationError, validate_manifest

__all__ = [
    "LOCAL",
    "MANIFEST_API_VERSION",
    "MANIFEST_FILENAME",
    "MCP_PLUGIN_API_VERSION",
    "MCP_SERVERS",
    "MISSING",
    "PLUGIN_API_VERSION",
    "SHIPPED",
    "CompiledMcpPlugin",
    "ConfigField",
    "ConfigKind",
    "ConfigSchema",
    "LaunchManifest",
    "LaunchPlan",
    "LoadedMcpPlugin",
    "McpConfigField",
    "McpConfigKind",
    "McpConfigResolutionError",
    "McpConfigSchema",
    "McpLaunchContext",
    "McpLaunchManifest",
    "McpLaunchPlan",
    "McpLaunchPlanner",
    "McpManifestValidationError",
    "McpPluginCatalog",
    "McpPluginDiagnostic",
    "McpPluginError",
    "McpServerManifest",
    "McpServerSpec",
    "PluginCapability",
    "SecretReference",
    "SecretValue",
    "UnknownMcpServer",
    "catalog",
    "compile_manifest",
    "diagnostics",
    "discover",
    "get",
    "install",
    "load_plugin",
    "parse_secret_reference",
    "resolve_config",
    "resolve_plugin_config",
    "scan",
    "validate_manifest",
]
