global:
  scrape_native_histograms: true

otlp:
  keep_identifying_resource_attributes: true
  promote_resource_attributes:
    - service.name
    - service.instance.id
    - service.version
    - theater.process.role

storage:
  tsdb:
    out_of_order_time_window: 10m
