"""Canonical harness contract modules.

Event types, launch-plan dataclasses, the Harness ABC, and observation
contracts live here. ``base.py`` re-exports everything in this package for
backward compatibility.
"""

from __future__ import annotations

from theater.harness.contracts.callbacks import (
    LaunchContext,
    LaunchPlanner,
    ModelDiscoverer,
    ModelDiscoveryContext,
    NativeChildrenContext,
    NativeChildrenReader,
    OperatorCandidateAdmitter,
    OperatorCandidateContext,
    ReceiptValidationContext,
    ReceiptValidator,
    ResumeContext,
    ResumePlanner,
    ScreenClassifier,
    ScreenContext,
    SourceFactory,
    StreamFloorContext,
    StreamFloorReader,
    TranscriptCandidatesContext,
    TranscriptCandidatesReader,
)
from theater.harness.contracts.channels import (
    ChannelBounds,
    ChannelCapability,
    ChannelDeclaration,
    ChannelHealth,
    ChannelHealthState,
    ChannelKind,
    SignalKind,
    SignalOwnership,
)
from theater.harness.contracts.context import ParticipantObservationContext
from theater.harness.contracts.events import (
    Event,
    EventKind,
    EventPath,
    TokenUsage,
    clip,
    clipper,
    last_screen_line,
    status_after,
    whole,
)
from theater.harness.contracts.harness import APPROVALS, Harness, LaunchParameterSupport
from theater.harness.contracts.launch import (
    LaunchPlan,
    NativeChild,
    ResumeLaunchOverlay,
    theater_binary,
)
from theater.harness.contracts.manifest import (
    MANIFEST_API_VERSION,
    PLUGIN_API_VERSION,
    HarnessManifest,
    HookChannelManifest,
    IdentityManifest,
    LaunchManifest,
    LineageManifest,
    ModelDiscoveryManifest,
    ObservationManifest,
    OtelChannelManifest,
    ScreenManifest,
    SourceManifest,
    UnavailableChannelManifest,
)
from theater.harness.contracts.observation import (
    HarnessObserver,
    ScreenConfidence,
    ScreenKind,
    ScreenReading,
)
from theater.harness.contracts.source import (
    Batch,
    History,
    HistoryPage,
    Source,
    SourceContractError,
    TrajectoryHistoryPage,
)
from theater.harness.contracts.trajectory import FactLink, ParsedRecord, TrajectoryFact

__all__ = [
    "APPROVALS",
    "MANIFEST_API_VERSION",
    "PLUGIN_API_VERSION",
    "Batch",
    "ChannelBounds",
    "ChannelCapability",
    "ChannelDeclaration",
    "ChannelHealth",
    "ChannelHealthState",
    "ChannelKind",
    "Event",
    "EventKind",
    "EventPath",
    "FactLink",
    "Harness",
    "HarnessManifest",
    "HarnessObserver",
    "History",
    "HistoryPage",
    "HookChannelManifest",
    "IdentityManifest",
    "LaunchContext",
    "LaunchManifest",
    "LaunchParameterSupport",
    "LaunchPlan",
    "LaunchPlanner",
    "LineageManifest",
    "ModelDiscoverer",
    "ModelDiscoveryContext",
    "ModelDiscoveryManifest",
    "NativeChild",
    "NativeChildrenContext",
    "NativeChildrenReader",
    "ObservationManifest",
    "OperatorCandidateAdmitter",
    "OperatorCandidateContext",
    "OtelChannelManifest",
    "ParsedRecord",
    "ParticipantObservationContext",
    "ReceiptValidationContext",
    "ReceiptValidator",
    "ResumeContext",
    "ResumeLaunchOverlay",
    "ResumePlanner",
    "ScreenClassifier",
    "ScreenConfidence",
    "ScreenContext",
    "ScreenKind",
    "ScreenManifest",
    "ScreenReading",
    "SignalKind",
    "SignalOwnership",
    "Source",
    "SourceContractError",
    "SourceFactory",
    "SourceManifest",
    "StreamFloorContext",
    "StreamFloorReader",
    "TokenUsage",
    "TrajectoryFact",
    "TrajectoryHistoryPage",
    "TranscriptCandidatesContext",
    "TranscriptCandidatesReader",
    "UnavailableChannelManifest",
    "clip",
    "clipper",
    "last_screen_line",
    "status_after",
    "theater_binary",
    "whole",
]
