"""Canonical harness contract modules.

Event types, launch-plan dataclasses, the Harness ABC, and observation
contracts live here. ``base.py`` re-exports everything in this package for
backward compatibility.
"""

from __future__ import annotations

from theater.harness.contracts.callbacks import (
    HookCorrelationContext,
    HookCorrelationExtractor,
    HookDecodeContext,
    HookDecoder,
    HookInstallContext,
    HookInstaller,
    HookInstallOverlay,
    LaunchContext,
    LaunchPlanner,
    ModelDiscoverer,
    ModelDiscoveryContext,
    NativeChildrenContext,
    NativeChildrenReader,
    OperatorCandidateAdmitter,
    OperatorCandidateContext,
    OtelCorrelationContext,
    OtelCorrelationExtractor,
    OtelDecodeContext,
    OtelInstallContext,
    OtelInstaller,
    OtelInstallOverlay,
    OtelSignalDecoder,
    ReceiptValidationContext,
    ReceiptValidator,
    ResumeContext,
    ResumePlanner,
    ResumePreflight,
    ResumePreflightContext,
    ScreenClassifier,
    ScreenContext,
    SourceFactory,
    StreamFloorContext,
    StreamFloorReader,
    TranscriptCandidatesContext,
    TranscriptCandidatesReader,
)
from theater.harness.contracts.channels import (
    ChannelBounds,
    ChannelCapability,
    ChannelDeclaration,
    ChannelFact,
    ChannelHealth,
    ChannelHealthState,
    ChannelKind,
    HookBinding,
    HookDeliveryMode,
    OtelBinding,
    OtelBounds,
    OtelCorrelation,
    OtelProtocol,
    OtelRecord,
    OtelSignal,
    SignalKind,
    SignalOwnership,
)
from theater.harness.contracts.context import ParticipantObservationContext
from theater.harness.contracts.events import (
    Event,
    EventKind,
    EventPath,
    TokenUsage,
    clip,
    clipper,
    last_screen_line,
    status_after,
    whole,
)
from theater.harness.contracts.harness import APPROVALS, Harness, LaunchParameterSupport
from theater.harness.contracts.launch import (
    ChannelCredential,
    LaunchPlan,
    NativeChild,
    ResumeLaunchOverlay,
    theater_binary,
)
from theater.harness.contracts.manifest import (
    MANIFEST_API_VERSION,
    PLUGIN_API_VERSION,
    HarnessManifest,
    HookChannelManifest,
    IdentityManifest,
    LaunchManifest,
    LineageManifest,
    ModelDiscoveryManifest,
    ObservationManifest,
    OtelChannelManifest,
    ScreenManifest,
    SourceManifest,
    UnavailableChannelManifest,
)
from theater.harness.contracts.observation import (
    HarnessObserver,
    ScreenConfidence,
    ScreenKind,
    ScreenReading,
)
from theater.harness.contracts.source import (
    Batch,
    History,
    HistoryPage,
    Source,
    SourceContractError,
    TrajectoryHistoryPage,
)
from theater.harness.contracts.trajectory import FactLink, ParsedRecord, TrajectoryFact
from theater.harness.contracts.values import freeze_json_mapping

__all__ = [
    "APPROVALS",
    "MANIFEST_API_VERSION",
    "PLUGIN_API_VERSION",
    "Batch",
    "ChannelBounds",
    "ChannelCapability",
    "ChannelCredential",
    "ChannelDeclaration",
    "ChannelFact",
    "ChannelHealth",
    "ChannelHealthState",
    "ChannelKind",
    "Event",
    "EventKind",
    "EventPath",
    "FactLink",
    "Harness",
    "HarnessManifest",
    "HarnessObserver",
    "History",
    "HistoryPage",
    "HookBinding",
    "HookChannelManifest",
    "HookCorrelationContext",
    "HookCorrelationExtractor",
    "HookDecodeContext",
    "HookDecoder",
    "HookDeliveryMode",
    "HookInstallContext",
    "HookInstallOverlay",
    "HookInstaller",
    "IdentityManifest",
    "LaunchContext",
    "LaunchManifest",
    "LaunchParameterSupport",
    "LaunchPlan",
    "LaunchPlanner",
    "LineageManifest",
    "ModelDiscoverer",
    "ModelDiscoveryContext",
    "ModelDiscoveryManifest",
    "NativeChild",
    "NativeChildrenContext",
    "NativeChildrenReader",
    "ObservationManifest",
    "OperatorCandidateAdmitter",
    "OperatorCandidateContext",
    "OtelBinding",
    "OtelBounds",
    "OtelChannelManifest",
    "OtelCorrelation",
    "OtelCorrelationContext",
    "OtelCorrelationExtractor",
    "OtelDecodeContext",
    "OtelInstallContext",
    "OtelInstallOverlay",
    "OtelInstaller",
    "OtelProtocol",
    "OtelRecord",
    "OtelSignal",
    "OtelSignalDecoder",
    "ParsedRecord",
    "ParticipantObservationContext",
    "ReceiptValidationContext",
    "ReceiptValidator",
    "ResumeContext",
    "ResumeLaunchOverlay",
    "ResumePlanner",
    "ResumePreflight",
    "ResumePreflightContext",
    "ScreenClassifier",
    "ScreenConfidence",
    "ScreenContext",
    "ScreenKind",
    "ScreenManifest",
    "ScreenReading",
    "SignalKind",
    "SignalOwnership",
    "Source",
    "SourceContractError",
    "SourceFactory",
    "SourceManifest",
    "StreamFloorContext",
    "StreamFloorReader",
    "TokenUsage",
    "TrajectoryFact",
    "TrajectoryHistoryPage",
    "TranscriptCandidatesContext",
    "TranscriptCandidatesReader",
    "UnavailableChannelManifest",
    "clip",
    "clipper",
    "freeze_json_mapping",
    "last_screen_line",
    "status_after",
    "theater_binary",
    "whole",
]
