"""Supported public frontend API for Theater clients and terminal providers.

The package is intentionally connect-only.  Importing it must never start a
daemon, terminal provider, or user interface.
"""

from theater.frontend._results import (
    AcceptedOperation,
    FrontendResult,
    JobsAwaitResult,
    OperationAwaitResult,
    Page,
    StateFollowResult,
)
from theater.frontend.capabilities import ConnectionChannel, ConnectionRole
from theater.frontend.client import (
    CapabilityUnavailable,
    ClientStateError,
    ConnectionLane,
    FrontendClient,
    FrontendClientConfig,
    FrontendClientError,
    FrontendResponseError,
    IdempotencyRequirementError,
    MethodRoleError,
    NegotiationError,
    RequestTimedOut,
    ResponseCorrelationError,
    ResponseValidationError,
)
from theater.frontend.dto import (
    Controls,
    Event,
    EventCursor,
    EventTransaction,
    HandshakeResult,
    Job,
    Operation,
    Participant,
    Provider,
    SnapshotPage,
    Workspace,
)
from theater.frontend.errors import ErrorCode, ErrorValue, FrontendError
from theater.frontend.provider import (
    CallbackHandler,
    CallbackRequest,
    CallbackResponse,
    ProviderClient,
    ProviderClientConfig,
    ProviderClientError,
    ProviderConnectionError,
    ProviderGenerationError,
    ProviderHandshakeError,
    ProviderHandshakeRefused,
    ProviderProtocolError,
)
from theater.frontend.transport import (
    FrontendTransportError,
    RequestUncertain,
    TransportBusy,
    TransportConnectionError,
    TransportProtocolError,
    TransportStateError,
)

__all__ = [
    "AcceptedOperation",
    "CallbackHandler",
    "CallbackRequest",
    "CallbackResponse",
    "CapabilityUnavailable",
    "ClientStateError",
    "ConnectionChannel",
    "ConnectionLane",
    "ConnectionRole",
    "Controls",
    "ErrorCode",
    "ErrorValue",
    "Event",
    "EventCursor",
    "EventTransaction",
    "FrontendClient",
    "FrontendClientConfig",
    "FrontendClientError",
    "FrontendError",
    "FrontendResponseError",
    "FrontendResult",
    "FrontendTransportError",
    "HandshakeResult",
    "IdempotencyRequirementError",
    "Job",
    "JobsAwaitResult",
    "MethodRoleError",
    "NegotiationError",
    "Operation",
    "OperationAwaitResult",
    "Page",
    "Participant",
    "Provider",
    "ProviderClient",
    "ProviderClientConfig",
    "ProviderClientError",
    "ProviderConnectionError",
    "ProviderGenerationError",
    "ProviderHandshakeError",
    "ProviderHandshakeRefused",
    "ProviderProtocolError",
    "RequestTimedOut",
    "RequestUncertain",
    "ResponseCorrelationError",
    "ResponseValidationError",
    "SnapshotPage",
    "StateFollowResult",
    "TransportBusy",
    "TransportConnectionError",
    "TransportProtocolError",
    "TransportStateError",
    "Workspace",
]
