"""Legacy 2.x bootstrap: one private `serve`, verified, then one TUI.

Core swallows a plugin load failure, so the wrapper proves the generated plugin
active on the serving instance before any prompt or UI starts.
"""

from __future__ import annotations

import asyncio
import contextlib
import json
import os
import secrets
import signal
import sys
from collections.abc import Mapping
from pathlib import Path

import theater

from .approval_v2 import require_plugin_active
from .constants import BOOTSTRAP_READY_TIMEOUT_SECONDS, PLUGIN_ACTIVE_TIMEOUT_SECONDS
from .http_v2 import OpenCodeV2Client, model_ref
from .native_plugin_v2 import PLUGIN_ID
from .server_discovery import parse_server_stdout_endpoint

_SETTINGS_SENTINEL = "__THEATER_BOOTSTRAP_SETTINGS__"
_PARENT_SENTINEL = "__THEATER_PACKAGE_PARENT__"

_LAUNCHER = f"""\"\"\"Generated by Theater: one verified private server, then one TUI.\"\"\"
import json
import sys

sys.path.insert(0, {_PARENT_SENTINEL!r})
from theater.harness.builtin.plugins.opencode.legacy_bootstrap_v2 import main

raise SystemExit(main(json.loads({_SETTINGS_SENTINEL})))
"""


class BootstrapError(RuntimeError):
    """The launch refused itself; the TUI never started."""


def bootstrap_path(config_path: Path) -> Path:
    return config_path.with_suffix(".bootstrap.py")


def render_legacy_bootstrap(settings: Mapping[str, object]) -> str:
    """The thin launcher written beside the config; all logic stays in this package."""
    parent = str(Path(theater.__file__).resolve().parent.parent)
    # Both literals travel quoted: JSON null/true/false are not Python, and a
    # path may hold an apostrophe.
    return _LAUNCHER.replace(repr(_PARENT_SENTINEL), repr(parent)).replace(
        _SETTINGS_SENTINEL, json.dumps(json.dumps(dict(settings)))
    )


def main(settings: Mapping[str, object]) -> int:
    credential = Path(str(settings["credential"]))
    # The location query and the cleanup run sync: async bodies avoid blocking calls.
    directory = str(Path.cwd().resolve())
    try:
        return asyncio.run(run(settings, directory=directory))
    except (asyncio.CancelledError, KeyboardInterrupt):
        return 143
    except Exception as exc:
        print(f"theater: refusing to open OpenCode: {exc}", file=sys.stderr)
        return 1
    finally:
        credential.unlink(missing_ok=True)


async def run(settings: Mapping[str, object], *, directory: str) -> int:
    """Own the serve process: verify it, admit the session, then run the TUI."""
    loop = asyncio.get_running_loop()
    # Signal callbacks run outside any task step, so the task is captured here.
    task = asyncio.current_task()
    assert task is not None
    for sig in (signal.SIGINT, signal.SIGTERM):
        with contextlib.suppress(NotImplementedError, ValueError):
            loop.add_signal_handler(sig, task.cancel)
    binary = str(settings["binary"])
    credential = Path(str(settings["credential"]))
    password = _mint_credential(credential)
    serve: asyncio.subprocess.Process | None = None
    drain: asyncio.Task[None] | None = None
    try:
        serve = await _spawn_serve(binary, settings, password)
        ready = settings.get("ready_timeout")
        timeout = (
            float(ready) if isinstance(ready, (int, float)) else BOOTSTRAP_READY_TIMEOUT_SECONDS
        )
        endpoint = await _read_endpoint(serve, timeout)
        drain = loop.create_task(_drain(serve.stdout))
        client = OpenCodeV2Client(endpoint=endpoint, token_file=credential)
        # Fail closed: prove the plugin on this very server before admitting anything.
        plugin_timeout = settings.get("plugin_timeout")
        await require_plugin_active(
            client,
            plugin_id=PLUGIN_ID,
            source_path=str(settings["plugin_source"]),
            directory=directory,
            timeout=(
                float(plugin_timeout)
                if isinstance(plugin_timeout, (int, float))
                else PLUGIN_ACTIVE_TIMEOUT_SECONDS
            ),
        )
        session_id = await _admit_session(client, settings)
        readback = await client.read_session(session_id)
        if readback.get("id") != session_id:
            raise BootstrapError(
                "the private server read back a different session id than admitted; "
                "refusing to open the TUI on it"
            )
        return await _run_tui(binary, endpoint, session_id, settings, password)
    finally:
        for sig in (signal.SIGINT, signal.SIGTERM):
            with contextlib.suppress(NotImplementedError, ValueError):
                loop.remove_signal_handler(sig)
        if drain is not None:
            drain.cancel()
            with contextlib.suppress(asyncio.CancelledError, Exception):
                await drain
        if serve is not None:
            await _terminate(serve)


def _mint_credential(path: Path) -> str:
    password = secrets.token_urlsafe(32)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        os.fchmod(handle.fileno(), 0o600)
        handle.write(password)
    return password


async def _spawn_serve(
    binary: str, settings: Mapping[str, object], password: str
) -> asyncio.subprocess.Process:
    env = {
        **os.environ,
        "OPENCODE_CONFIG": str(settings["config"]),
        "OPENCODE_SERVER_PASSWORD": password,
    }
    # A resume overlay's database wins: it names the predecessor's lineage.
    env.setdefault("OPENCODE_DB", str(settings["database"]))
    return await asyncio.create_subprocess_exec(
        binary,
        "serve",
        "--hostname",
        "127.0.0.1",
        "--port",
        "0",
        env=env,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.DEVNULL,
    )


async def _read_endpoint(serve: asyncio.subprocess.Process, timeout: float) -> str:
    """Read stdout until the documented banner; never a fixed sleep."""
    assert serve.stdout is not None
    loop = asyncio.get_running_loop()
    deadline = loop.time() + timeout
    while True:
        remaining = deadline - loop.time()
        if remaining <= 0:
            raise BootstrapError("the private server did not announce its endpoint in time")
        try:
            line = await asyncio.wait_for(serve.stdout.readline(), remaining)
        except TimeoutError as exc:
            raise BootstrapError(
                "the private server did not announce its endpoint in time"
            ) from exc
        if not line:
            raise BootstrapError("the private server exited before announcing its endpoint")
        try:
            endpoint = parse_server_stdout_endpoint(line.decode("utf-8", errors="replace"))
        except ValueError as exc:
            raise BootstrapError(str(exc)) from exc
        if endpoint is not None:
            return endpoint


async def _drain(stream: asyncio.StreamReader | None) -> None:
    """Keep the server's stdout moving so it never blocks on a full pipe."""
    if stream is None:
        return
    with contextlib.suppress(asyncio.CancelledError, ConnectionError, ValueError):
        while await stream.read(65_536):
            pass


async def _terminate(process: asyncio.subprocess.Process) -> None:
    if process.returncode is not None:
        return
    with contextlib.suppress(ProcessLookupError):
        process.terminate()
    try:
        await asyncio.wait_for(process.wait(), 5.0)
    except TimeoutError:
        with contextlib.suppress(ProcessLookupError):
            process.kill()
        with contextlib.suppress(Exception):
            await process.wait()


async def _admit_session(client: OpenCodeV2Client, settings: Mapping[str, object]) -> str:
    """Resume the exact session, or create the pre-minted one; no prompt is sent here."""
    resume = settings.get("resume")
    if isinstance(resume, str) and resume:
        readback = await client.read_session(resume)
        if readback.get("id") != resume:
            raise BootstrapError(
                "the private server read back a different session id than the resume target; "
                "refusing to continue it"
            )
        return resume
    model = model_ref(str(settings["model"])) if settings.get("model") else None
    session_id = settings.get("session_id")
    return await client.create_session(
        directory=None,
        model=model,
        session_id=session_id if isinstance(session_id, str) and session_id else None,
    )


async def _run_tui(
    binary: str,
    endpoint: str,
    session_id: str,
    settings: Mapping[str, object],
    password: str,
) -> int:
    argv = [binary, "--server", endpoint, "-s", session_id]
    prompt = settings.get("prompt")
    if isinstance(prompt, str) and prompt:
        argv += ["--prompt", prompt]
    tui_env = settings.get("tui_env")
    env = {
        **os.environ,
        "OPENCODE_SERVER_PASSWORD": password,
        **({str(k): str(v) for k, v in tui_env.items()} if isinstance(tui_env, Mapping) else {}),
    }
    tui = await asyncio.create_subprocess_exec(*argv, env=env)
    loop = asyncio.get_running_loop()
    for sig in (signal.SIGINT, signal.SIGTERM):
        with contextlib.suppress(NotImplementedError, ValueError):
            loop.add_signal_handler(sig, _forward_signal, tui, sig)
    try:
        return await tui.wait()
    finally:
        for sig in (signal.SIGINT, signal.SIGTERM):
            with contextlib.suppress(NotImplementedError, ValueError):
                loop.remove_signal_handler(sig)
        if tui.returncode is None:
            # Cancellation lands here before the forwarders do; the TUI is ours to reap.
            await _terminate(tui)


def _forward_signal(process: asyncio.subprocess.Process, sig: signal.Signals) -> None:
    if process.returncode is None:
        with contextlib.suppress(ProcessLookupError):
            process.send_signal(sig)


__all__ = [
    "BootstrapError",
    "bootstrap_path",
    "main",
    "render_legacy_bootstrap",
    "run",
]
