"""Legacy 2.x launch bootstrap: one private `serve`, verified, then one TUI.

2.x loads configured plugins per location and core swallows a plugin failure,
so the legacy route cannot trust the launch plugin to enforce approval by
itself. This wrapper owns exactly one stock private server: it reads the
endpoint banner, proves the generated plugin active on that same server,
creates (or resumes) the exact session with the enforced policy, and only then
opens the stock TUI on it — `--server <url> -s <id>`, prompt delivered once.
Any failure exits nonzero before the TUI starts and terminates only its own
backend; the credential is minted in memory and a 0600 file, never in argv.
"""

from __future__ import annotations

import asyncio
import contextlib
import json
import os
import secrets
import shutil
import signal
import sys
from collections.abc import Mapping
from pathlib import Path

import theater

from .approval_v2 import apply_session_policy, require_plugin_active
from .constants import BOOTSTRAP_READY_TIMEOUT_SECONDS
from .http_v2 import OpenCodeV2Client, model_ref
from .native_plugin_v2 import PLUGIN_ID
from .server_discovery import parse_server_stdout_endpoint

_SETTINGS_SENTINEL = "__THEATER_BOOTSTRAP_SETTINGS__"
_PARENT_SENTINEL = "__THEATER_PACKAGE_PARENT__"

_LAUNCHER = f"""\"\"\"Generated by Theater: one private OpenCode server, verified, then one TUI.\"\"\"
import sys

sys.path.insert(0, {_PARENT_SENTINEL!r})
from theater.harness.builtin.plugins.opencode.legacy_bootstrap_v2 import main

raise SystemExit(main({_SETTINGS_SENTINEL}))
"""


class BootstrapError(RuntimeError):
    """The launch refused itself; the TUI never started."""


def bootstrap_path(config_path: Path) -> Path:
    return config_path.with_suffix(".bootstrap.py")


def render_legacy_bootstrap(settings: Mapping[str, object]) -> str:
    """The thin launcher written beside the config; all logic stays in this package."""
    parent = str(Path(theater.__file__).resolve().parent.parent)
    return _LAUNCHER.replace(_PARENT_SENTINEL, parent).replace(
        _SETTINGS_SENTINEL, json.dumps(dict(settings))
    )


def main(settings: Mapping[str, object]) -> int:
    try:
        return asyncio.run(run(settings))
    except Exception as exc:
        print(f"theater: refusing to open OpenCode: {exc}", file=sys.stderr)
        return 1


async def run(settings: Mapping[str, object]) -> int:
    """Own the serve process: verify it, admit the session, then run the TUI."""
    binary = shutil.which(str(settings["binary"])) or str(settings["binary"])
    credential = Path(str(settings["credential"]))
    password = _mint_credential(credential)
    serve: asyncio.subprocess.Process | None = None
    drain: asyncio.Task[None] | None = None
    try:
        serve = await _spawn_serve(binary, settings, password)
        timeout = float(settings.get("ready_timeout") or BOOTSTRAP_READY_TIMEOUT_SECONDS)
        endpoint = await _read_endpoint(serve, timeout)
        drain = asyncio.get_running_loop().create_task(_drain(serve.stdout))
        client = OpenCodeV2Client(endpoint=endpoint, token_file=credential)
        session_id = await _admit_session(client, settings)
        await require_plugin_active(
            client,
            plugin_id=PLUGIN_ID,
            source_path=str(settings["plugin_source"]),
            directory=os.getcwd(),
        )
        await apply_session_policy(client, session_id, approval=str(settings["approval"]))
        readback = await client.read_session(session_id)
        if readback.get("id") != session_id:
            raise BootstrapError(
                "the private server read back a different session id than admitted; "
                "refusing to open the TUI on it"
            )
        return await _run_tui(binary, endpoint, session_id, settings, password)
    finally:
        if drain is not None:
            drain.cancel()
            with contextlib.suppress(asyncio.CancelledError, Exception):
                await drain
        if serve is not None:
            await _terminate(serve)
        credential.unlink(missing_ok=True)


def _mint_credential(path: Path) -> str:
    password = secrets.token_urlsafe(32)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        os.fchmod(handle.fileno(), 0o600)
        handle.write(password)
    return password


async def _spawn_serve(
    binary: str, settings: Mapping[str, object], password: str
) -> asyncio.subprocess.Process:
    env = {
        **os.environ,
        "OPENCODE_CONFIG": str(settings["config"]),
        "OPENCODE_DB": str(settings["database"]),
        "OPENCODE_SERVER_PASSWORD": password,
    }
    return await asyncio.create_subprocess_exec(
        binary,
        "serve",
        "--hostname",
        "127.0.0.1",
        "--port",
        "0",
        env=env,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.DEVNULL,
    )


async def _read_endpoint(serve: asyncio.subprocess.Process, timeout: float) -> str:
    """Read stdout until the documented banner; never a fixed sleep."""
    assert serve.stdout is not None
    loop = asyncio.get_running_loop()
    deadline = loop.time() + timeout
    while True:
        remaining = deadline - loop.time()
        if remaining <= 0:
            raise BootstrapError("the private server did not announce its endpoint in time")
        try:
            line = await asyncio.wait_for(serve.stdout.readline(), remaining)
        except asyncio.TimeoutError as exc:
            raise BootstrapError(
                "the private server did not announce its endpoint in time"
            ) from exc
        if not line:
            raise BootstrapError("the private server exited before announcing its endpoint")
        try:
            endpoint = parse_server_stdout_endpoint(line.decode("utf-8", errors="replace"))
        except ValueError as exc:
            raise BootstrapError(str(exc)) from exc
        if endpoint is not None:
            return endpoint


async def _drain(stream: asyncio.StreamReader | None) -> None:
    """Keep the server's stdout moving so it never blocks on a full pipe."""
    if stream is None:
        return
    with contextlib.suppress(asyncio.CancelledError, ConnectionError, ValueError):
        while await stream.read(65_536):
            pass


async def _terminate(process: asyncio.subprocess.Process) -> None:
    if process.returncode is not None:
        return
    with contextlib.suppress(ProcessLookupError):
        process.terminate()
    try:
        await asyncio.wait_for(process.wait(), 5.0)
    except asyncio.TimeoutError:
        with contextlib.suppress(ProcessLookupError):
            process.kill()
        with contextlib.suppress(Exception):
            await process.wait()


async def _admit_session(client: OpenCodeV2Client, settings: Mapping[str, object]) -> str:
    """Resume the exact session, or create the pre-minted one; no prompt is sent here."""
    resume = settings.get("resume")
    if isinstance(resume, str) and resume:
        readback = await client.read_session(resume)
        if readback.get("id") != resume:
            raise BootstrapError(
                "the private server read back a different session id than the resume target; "
                "refusing to continue it"
            )
        return resume
    model = model_ref(str(settings["model"])) if settings.get("model") else None
    session_id = settings.get("session_id")
    return await client.create_session(
        directory=None,
        model=model,
        session_id=session_id if isinstance(session_id, str) and session_id else None,
    )


async def _run_tui(
    binary: str,
    endpoint: str,
    session_id: str,
    settings: Mapping[str, object],
    password: str,
) -> int:
    argv = [binary, "--server", endpoint, "-s", session_id]
    prompt = settings.get("prompt")
    if isinstance(prompt, str) and prompt:
        argv += ["--prompt", prompt]
    tui_env = settings.get("tui_env")
    env = {
        **os.environ,
        "OPENCODE_SERVER_PASSWORD": password,
        **({str(k): str(v) for k, v in tui_env.items()} if isinstance(tui_env, Mapping) else {}),
    }
    tui = await asyncio.create_subprocess_exec(*argv, env=env)
    loop = asyncio.get_running_loop()
    for sig in (signal.SIGINT, signal.SIGTERM):
        with contextlib.suppress(NotImplementedError, ValueError):
            loop.add_signal_handler(sig, _forward_signal, tui, sig)
    try:
        return await tui.wait()
    finally:
        for sig in (signal.SIGINT, signal.SIGTERM):
            with contextlib.suppress(NotImplementedError, ValueError):
                loop.remove_signal_handler(sig)


def _forward_signal(process: asyncio.subprocess.Process, sig: signal.Signals) -> None:
    if process.returncode is None:
        with contextlib.suppress(ProcessLookupError):
            process.send_signal(sig)


__all__ = [
    "BootstrapError",
    "bootstrap_path",
    "main",
    "render_legacy_bootstrap",
    "run",
]
